# Project-wide Gradle settings.

# JVM args
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# Enable Gradle configuration on demand
org.gradle.configureondemand=true

# Enable parallel builds
org.gradle.parallel=true

# Android build cache is deprecated; removed completely
# android.enableBuildCache=true  <- REMOVED

# Kotlin compiler options
kotlin.code.style=official