name: Android Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan-dev glslang-dev glslang-tools

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleDebug --no-daemon \
            -Pandroid.externalNativeBuild.cmake.arguments="-DVulkan_INCLUDE_DIR=/usr/include"
